version: "3"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: abc
      MYSQL_DATABASE: abc
    ports:
      - "3306:3306"

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    restart: on-failure
